package com.uit.cloud.kubernetes;

/*
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */

import com.github.kubesys.kubernetes.ExtendedKubernetesClient;
import com.github.kubesys.kubernetes.api.model.VirtualMachine;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDisk;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDiskImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineNetwork;
import com.github.kubesys.kubernetes.api.model.VirtualMachinePool;

import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.ConfigBuilder;

/**
 * @author wuheng@otcaix.iscas.ac.cn
 * @author wuyuewen@otcaix.iscas.ac.cn
 * @author liuhe@otcaix.iscas.ac.cn
 *
 * @version 1.3.0
 * @since   2019/9/3
 *
 */
public class AbstractTest {

    public static Config config = new ConfigBuilder()
            .withApiVersion("v1")
            .withCaCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ETXpNVEV5TXpFd09Gb1hEVE13TURNeU9URXlNekV3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHVhCkZWZ3lsSnJqMFFRam5SN3VEaDQrSVdEQ0NYZDd4cXJ6SXpDQVFVTE5ZUE04OVlYc21VaE85MFBBSFFxUXhvOXoKd2N5TWwwdGR3WC9ESWE3bFcyeDhsZEtEM3RaZWVoNS8wMzJralVqcGhvM0NaV0Fhbnl6TW4yWkJQUkg4Y1FkdgowZW9FNUFQWEZvU29Cdnl6L3puSGl1WGtUcy93QXJXTTZqZmxpbDdSZlRhbUdJNGJiMHNCanQ2TDFLdG4xYkhzClNOVkpNYS9WNWFmVG1YaUJ5REZtYnA2aXRnOHd1MU5pU25yQWdzRWZWOWEwQVhJYnFJL0lZQk1IcHorcFRnNkcKbE5yRzZaZXhrOUtnRVZsbXlwL01ybkUwY0wvNWYzQmZ4cU1hYVhsV3BQcFpWZ05ZeURsdXE0YUxMUXFqekdRVwo3dDlWUjdsYVNHZ0k4aXJBYzVFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDc0F6WWJhekhWd3RrTjVzQ0RpdmNBd0E5ckgKZk81akdlNzE5K1JybUE3Z2NGUHdHeU9OQVFPanNzMjBjWUlYRnYybFBWZC9TZ2VZRythT3FobDVlOEVlcktsYwoxcTFYaXdUR0dXQkNYVDEyRlVOS0JaTnVOYnEveHY3MG9XM3NabmtQSitkbEthYmhWM2Fla05sN1JKK3pxVTJJCmc1ZEtiMHAzQmp1U2lxTldna0JWUnhscTBtZnZMZ1JwREx3Q3JZTGhmUk9IN21oeFJuMVgvWjh0bTRxYktOd3MKQ1VPclBTTFVPODkzS1M3WldGd0IrNVFqZ3pIY1l0N3ZhelEyckJVditRT29xdlR0b1MwNjBOdkRXRUtFd0FRcgpndWtmK3FsOGRGMCtiQkFDOCtiNG00VytlWHJWUkI1UjFYMkRDY2kvTEdlenFrSWRFYXhjNUh4K21OST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
            .withClientCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJSkd5MXlzc2d6aFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBek16RXhNak14TURoYUZ3MHlNVEF6TXpFeE1qTXhNVEZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVEWjdBS0E4OGZpZGFCNWsKN0hiTVYrOXlHRnNsZnNseWZzMkZwM1hNRTlJNTUxOGpBTEprVXhoRytVQ0x2WGNXLzg4WUVidTNwdDJlK3B2MwprSUdlUUJyVGJNdFUrT1dMVWZLY1AxcHdpRFZ2RjV0cFNOUlpRbUs4bzd4Y0c5MERsTHVobmdHekxCZWRoZkp3CnM5QmFGVW9GR1VwajRGaGZYZmJSdU5kTkx4aHNVaDFzQ1JDOUR5QW9jSUpyL1VXcTdHV2dhL1ZWQWJJUUJGeFgKdHI1bnNmRlRsTnlUbTFNQzNBSVVyTlM1MTQ5bzJoZFR5OXFFSU9TbHh1MDZSbmMybGZOT1NmSkYwNkZxKytBRApGT1IrNnA1WW8wandsdTlsWUtDTVdxMllFSzR0TlorcUE1eTFkd2dPbDAxKzNXMk9aTC8wTTJKWE5aWTJoWHJICkJqb1ord0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFETWFoVkFNRTNod0xFN0NHa082MWhXZ1NUbmxYY1hVUmNIaQpXRnNtZHBlMHhQUm1zN2V5eDM1NzJuRmdQN3RSWjJRblN2UVROZEg0Zm5EWUR0YTgxZmNIQjhMUmQyQU5PRzFtCmNzODBpWmdYeUg0OEJpZ3l0WnVScjdWV1c5UGxvcTlSR0xCaEJCdnBxL1JOMXlld21TRTR5aE5meWxMbm9JRmYKeEhhUzBad2Q4YXBsd2RtMUhRNXVKUEZ5Nll4Y3VNdjFWanFvbzJCQWFnbEU3bjNGa3VaQkJ2K0tOSEE1b3V0OQo2L00wSFh2M2YwOHhEMnNtaDZ6b0UxWnRDYmpDNlBJUWZPSjRtQXliQnY1aXo5anRyR1dBbzQvY2dqdnpETzdECkIySFNkeENGa2g5ZGlQUURuVGEvSFdmTTd4dWhxODdTeVVVeG9nYjBQMzdZRWt4SGhEOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
            .withClientKeyData("LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdURaN0FLQTg4ZmlkYUI1azdIYk1WKzl5R0ZzbGZzbHlmczJGcDNYTUU5STU1MThqCkFMSmtVeGhHK1VDTHZYY1cvODhZRWJ1M3B0MmUrcHYza0lHZVFCclRiTXRVK09XTFVmS2NQMXB3aURWdkY1dHAKU05SWlFtSzhvN3hjRzkwRGxMdWhuZ0d6TEJlZGhmSndzOUJhRlVvRkdVcGo0RmhmWGZiUnVOZE5MeGhzVWgxcwpDUkM5RHlBb2NJSnIvVVdxN0dXZ2EvVlZBYklRQkZ4WHRyNW5zZkZUbE55VG0xTUMzQUlVck5TNTE0OW8yaGRUCnk5cUVJT1NseHUwNlJuYzJsZk5PU2ZKRjA2RnErK0FERk9SKzZwNVlvMGp3bHU5bFlLQ01XcTJZRUs0dE5aK3EKQTV5MWR3Z09sMDErM1cyT1pMLzBNMkpYTlpZMmhYckhCam9aK3dJREFRQUJBb0lCQUd3YlpQSklGNXcxdUVMTApXNVUrWHN2WWRSQUFKYkFUandNRm9FTlhxVTJVbVhERWIybFFSL3BRREE3cEoxa29rN0hLbXFpRmp0RDV6UHZzCkhreUxGUkV2N1JZeStnb2J4RGh5ZGVua0xKaHpLMkFpVDVaek1ITDZPUlNxVFMvNDg4b01sMXVBU2VNOWRLK1EKU1QzdHI0QkE4VjhYUGlnQ0ZPMnpGUDh5TTFUSU5IR3hJRnNheDJSNGVCQnNhclcyM0NqRlo5UkZmTklHeE41MwpWQ1ZYYzFmN0xiUUVzTXgrSVk0VWpZMUhlZkozZG5IUHdOeGV1Q2trTVljMEpvMmY4WGpWaDlzZTBqWWgrR2hRCjVLOUNJTWtzRVJ2ZjJRazZHb296K295UXA3RUx5R3poTXl6cCs2bkxCaFZwS1BOVGZrL3JqNWo4K29uZ2k4NVcKRVpWeXV6a0NnWUVBNFZVSjZIQ2loUGl6MmNrVWl0RGhmaXBQTDkzbUdJRWpuaDk4WGF4NHROVm40WmQ0dkwzMQpTOGJMOVhXTHhqdmdkbW82aG1HMlhBU2ZCMUFPekFRVHB4Mk95RkhVcEF2VENpbXJkK2ZwTGdyaHYrVGN6NklyCjJWYmFkQTNrV0RkTDk3aldJSENucGNRaWxXNTVqajJEMEFLUnY4bmJEWTE3bjBINXRUd1hZZFVDZ1lFQTBVakYKcldoUUVFMXVFVXJPZFdkYWxaRkVvcmVtdmVGQWtiM3NFUmVscEVaczJsRHIzVXpJYXk2WTEwVjRDcjBLZnRvaAo0MTlMYXQyRnlUTlJmVkxWTXdNUTBYK0s4dzA4RXR6d2hMUjVjU0pSanVMMVBQcE90Ui9MblU0VzRMSVZPSzlEClRiakJsRW9vZm9xWFNZYmdaTytweXFnVUh0aDYwNmU3Z3JHR3BJOENnWUFvMm13amNsaGsxMXAwUDlxem1FOXAKdW00RTlheEVBUlhlRTBOUEVIZ0tBUzhHWFpvTVRqeHM4cXdENHIzbXdQQmZSNzg0b2ZxWUVGWnMwdno3ekRscgo4UlgwQjdJUDAvejlPTFRYMW5vV1dPNjVCZHRxNGJJbGczT3oydGp0allqK2JzcVRzeGtTR3M5U1hHYzVmTG1yCk91d0Y0NmtOZWZ0UjBucGRlM21aeVFLQmdRQ0d0enRYMWsvRFRyUk5PVVFRMnNpNmdsb1dDL1d2UUhIWjN0RTQKWjJwZWhsN0hZVk9Tamp4c2tnQWNna0UxV0Y2TExVcW5HODVtS2RaV24wd1RTZUNuQjVBcDZ0bThmb1p1OWYxMAp6dDlsYmR2bUNENG9WRStaMDYrendIS0ZqTnlRTW5FMmRIbFhSUzB2MTNKdkIvMGx2QWdseFcrK00wZE5PeWsrCmhadlFEUUtCZ0Q5UFkranByYnZndnA3QTNDTmxwK25OZlVjT1BJNUk5MVdVdGFTQ2QrY1dPV0lucVZvMzh5T0YKTkVEVEV0dmViUWk0Wld6T0k3aWtnczhWblAzd3BmY3hYNkJmbWNtL2pPb040YWtKV2RvdU9HMTlCTGNUb2dtUQpublVId1YzUjNRU0tKZm0zZEZ3WHBHYWNoQjBwLzFFVXZweGY0RWhuRzhVZDJVNEVaaWlMCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==")
            .withMasterUrl("https://172.16.1.27:6443")
            .build();

    public static ExtendedKubernetesClient getClient() throws Exception {
        return new ExtendedKubernetesClient(config);
    }

    public static VirtualMachine getVMByName(String name) throws Exception {
        return getClient().virtualMachines().get(name);
    }

    public static VirtualMachineImage getVMImageByName(String name) throws Exception {
        return getClient().virtualMachineImages().get(name);
    }

    public static VirtualMachineDisk getVMDiskByName(String name) throws Exception {
        return getClient().virtualMachineDisks().get(name);
    }

    public static VirtualMachinePool getVMPoolByName(String name) throws Exception {
        return getClient().virtualMachinePools().get(name);
    }

    public static VirtualMachineDiskImage getVMDiskImageByName(String name) throws Exception {
        return getClient().virtualMachineDiskImages().get(name);
    }

    public static VirtualMachineNetwork getVMNetworkByName(String name) throws Exception {
        return getClient().virtualMachineNetworks().get(name);
    }
}
