package com.uit.cloud.kubernetes;

/*
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */

import com.github.kubesys.kubernetes.ExtendedKubernetesClient;
import com.github.kubesys.kubernetes.api.model.VirtualMachine;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDisk;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDiskImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineNetwork;
import com.github.kubesys.kubernetes.api.model.VirtualMachinePool;

import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.ConfigBuilder;

/**
 * @author wuheng@otcaix.iscas.ac.cn
 * @author wuyuewen@otcaix.iscas.ac.cn
 * @author liuhe@otcaix.iscas.ac.cn
 *
 * @version 1.3.0
 * @since   2019/9/3
 *
 */
public class AbstractTest {

    public static Config config = new ConfigBuilder()
            .withApiVersion("v1")
            .withCaCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXpNVEF5TURBek5Wb1hEVEk1TVRJeU9EQXlNREF6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTktmCmJhcDI1RjNTVm85KzlKdWhsOUtWMU1DMFBHSFA2WXA4dWZXQ0l4NmdZSWRsM3Zma3ExeHNRZjZDZmVpRlB3S0YKOFBzZjhGbkl6dVloYnJWclRiSnVDamJJOWxtT3VzQ1phdkh1UGV5N0luTWxxbVFCd3JXQ2RYblhhTDNzT0FPaQp1REgxVVlNSXhLMlhaV3d0Zit3R2p1NFBMZjY1VnVOVDRNS3JMOXRPNWJQL25mUU5KTjRoM3J1OFY5UUFPMkwvCjB3SGdzTHVEVWQwRTA5RzV2c0NQNnZkeS9ORmlFaXgrOWlwUFVuZFVBbmpyQVEvblVUWFhMUFZLTWxjeDd6UnUKVzNGNnBYQ2NrSHgzSjQ2S3FhbmllaDBmNzRxN00zbzR5MUdnbmZCeEFSOFpDR2JOOXQxWkZ1YjV3YWx4Q2JRegprU3RXYVMzUkxudWFib2hwdVljQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBNWIxRnZ2MUhlTW1heWRhVlVteUd6OWtXckwKeko0TWNOZWFjQW1LUklXQ21ublFNZWFsTWdBQkY2UU1JMU1GTlczdEdBZ0liSDVQUzA0NXNPNXQ4b0gzdjVDSAoyUWgwZmtVTUROU0hIK1BEVXNENVVUTXRleVVyelVpY2oycmJPSFU5YUxma0lFd3hRZUlvL01YSGZwOTI5Ym5YCkg0a2Y5cFphZFhXREI3cFRnbXJGRjhicFJMcDFkY05oV0dscUo0S1gxSjlqZHJraUNvOFp0U003bGlZNkpUT1QKUnlzcEVPdzlhbitNaEJUeW83V3Q5TGg4d2Q1MkZ5dm02YStiNTVjU3lRdk5pQVFhOEs5QUdQYWNWTGcwalpkRApNcDhmbldWRWI1YS9ZdlJIcEhPT2tKV28yTyttVklnbXRuZ0dLMDJRZ1duYlo1UU9OUnJJN2JWdGl2RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
            .withClientCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJRDZEUlB4M1NVSlV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RFeU16RXdNakF3TXpWYUZ3MHlNREV5TXpBd01qQXdNemhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXMveE9WVHVmVytJdUtVQlAKR2MyaUVsbjkxN3k5OVBTSWhVSXB6OVVsZUZTTGROR040aUt2R1REUXlCaENJbmhpbC9rQVVEcklaQm44OUxYOQpEejg3d0wrWG0vMFJLUUVTbkhXbWxDVE5MWVdUK3dPWW5GdklHbkJqWFZzdG9tZlI4TVhRbURkN1V5cjZHa2drCjVuT3I2ajJscDcwWmlJQWFhMEk3RnJoelNIcURDUEJIN1F2czNrdll6eTgwUkhic21aVWxrdHY4TTRUN3dwYmoKNG5TNkZoN1dDbEVHbTZtL3Y2WXJCWkdlaWlHOHM1dVpRK3Y2enJJMzMzVU5MeWxhUEdzQmxkdGNJUGhvNzJuVgpScW9JNktBaUZSakUwU3ZDQUovaSswT3dIZFVVYlNTMXdveGlkUmV1eGpZZWdCUzFKY3FYOXlYWnl0eHhPVlNhCnJibWRsUUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBcHUxQjR1LytFbzlnempLYURFaDd3anJyQkcrV3NTcHVPUwpubisvOGxnOVpjTXV5VE4rMW9qL002dkdiOXo0am5SclhyYXkzd1cyRDNrTmRDVU9RemFaazA5T3JTdFJZSkdMClZFcTkvcTZVc1U4YlN2a1g0c1V0aUNOdFo2U2d6N2RmUXV3aGxKQTBqOVZNY1ByY0VqUjlnUmxWMXI2dlM4OTQKZDQ2T0trbE5DM1FpdmdZSjQ5SFpyajQvZ2ttSEtYMUd1VVRLMUFuL1lRdzFNNWJmcHdHVTBmTmF5cE9lNFd0UApuOGUxNk1LWEgwdFVJYUNrazJoZ0U0c0Rydm5RbVNVTTlIVVlhU0R5R3ppR3VOaDNjSm84WC9laVRSZVRVTTgyCmlidFB4c2ZtcS9wTlI5aTNJTTVocjBBVnl6TDI3bWoyZUFraVQrdG43K0dETDNLRzhxaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
            .withClientKeyData("LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcy94T1ZUdWZXK0l1S1VCUEdjMmlFbG45MTd5OTlQU0loVUlwejlVbGVGU0xkTkdOCjRpS3ZHVERReUJoQ0luaGlsL2tBVURySVpCbjg5TFg5RHo4N3dMK1htLzBSS1FFU25IV21sQ1ROTFlXVCt3T1kKbkZ2SUduQmpYVnN0b21mUjhNWFFtRGQ3VXlyNkdrZ2s1bk9yNmoybHA3MFppSUFhYTBJN0ZyaHpTSHFEQ1BCSAo3UXZzM2t2WXp5ODBSSGJzbVpVbGt0djhNNFQ3d3BiajRuUzZGaDdXQ2xFR202bS92NllyQlpHZWlpRzhzNXVaClErdjZ6ckkzMzNVTkx5bGFQR3NCbGR0Y0lQaG83Mm5WUnFvSTZLQWlGUmpFMFN2Q0FKL2krME93SGRVVWJTUzEKd294aWRSZXV4alllZ0JTMUpjcVg5eVhaeXR4eE9WU2FyYm1kbFFJREFRQUJBb0lCQURzanBpRi9hOGRuTkQrOQpyOEFNdnpwRWM1SVZwRnorbEhVazNsUTU5d3ZveThIZ3NUd2lwV0lqbGhhSlVnRzlpTGZpeTJXUlN4TUpMd0xCClladEc3YjFSdHVFOGNBMEhHelJwdkFobFp6MlQ3S0hIOXJjNXVUQm15Vjk5ZkNzbTdlYXRPUE1yRjh5bURIUGkKVEsya1NGSzVXdHNZMlhEdWxyK3pqWExUdkoyTmhySk9NMW1vUEFFd3hOcjNDQlhQTEVKdU5WVGdvVlFOUHBNTgpQT08wU3UrRDJGZ2JLWmllYWFUNXowQ1hpZnZ1a0RjbENTTWNWano1bDZVV2VxUnpsQTdvdkRqanFoVEdYOWRUCkRCSVppZ0NvS0kvWXBzeEVIQnBWM2RURStOMURVN2JMeEZCK2s3VzVRdThOMURuaVhmL0UrcFlXcDVPV3owaWcKdnFkS3FzRUNnWUVBMFpjNm1NajRteUQwVG0rTnNuY2t4OHVxVDBvdDlBTm5sQTVHWjZibTd2SnhBRWRNWUt3Nwo3SlVzbng2emJZeFFhYWxPMStaU1MvOEhPYVBmbTNRV1h2WjRQb2dUWUVVT1FUWWpuREhnYllNVHlFcHhHSlA5CkVheTA1ZUFpTDN2TEJhZ3JwNStqODlxRGgrTVRMTWc4amd4Tmxqeko1Zks5T0lOODA1bkY4TjBDZ1lFQTI5YmsKSmJFRzBTUGhVdTRsejFtNm85aWNjd0UxWTJqaTBBNGt5UGkwV2VVWEpHUUptT0o0aFdhV2dOMWxRZ3VnRHRwbQpQWUFPK3Jhb1FGN1h0bENCZ3dHelltNWl4N1pYdFpPNGkvL2VkU2wycHZnNFJkN3lKbGtzUUxmbkVJWlFWRGY4Ck9tR01TOWJYR1NvZnBkbm9wNmdjYkVmb3FqclFJWWo2QUJmYitCa0NnWUFLY3JKK0dVNmpWUkk0c3NEcWk1dnUKeGMxWXBJY0Q2Z09JMHVsWmsyMWhyZjVLR0VQTGNlcU8wYVRtemIzK0VRZVZMTlo4VnNQMWUrSWRVbmo4STk1VgpuNDNBK0VHWEEvcEE3L1Q0ZlZnRnZZb0g2d1lXUnBKUUJqOENVcGtCcXZjazhnd3pEL2M1V2NSQ3l1UVMwR3lNClhEcWw2YVBhN2EzWEdsN25vWHZIbFFLQmdFWFRhNFBOUnEwSENIcWV5Y09pYkhXK1IzTC8zMFZEKzBhNk4xVGUKS2VxanFVWVZ3RGFmT0VpbTNRYnhTMGcvQ1FldXR1cXgwaEF3RkNEZC93WVpiQW1BY01uQzVmMHBIWksrNk04Two1a213Y2M5MjUrakpkNEJXc29lYjRmaU5zTllQTWo0WTNjYjQ1amxIOStWbDRVL2ZSYWZlN3plaWxwa1FPTmZ1CnZCK0JBb0dCQUlRNmszMWtvODVNamVmb1RXT1FGT2lxL2ZZdlNJYStwTEh3cjRoTVlMY3JGODNtbVpiQ0kreE0KaDRuRnUrWW53N3JDeXNDNnJ1bVZSbndYaGFYS1VDaUFPQkFxUjNNN1B0K2QwTngxN1ZLM3pmYXI2MXJEcVRHMQpLV3U1Z2Z6aTJjaFhDMm9tdHprNDdOSEhhUllueFBFNlpidUNubFcxY2FybUJINzhkU0dECi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==")
            .withMasterUrl("https://172.16.1.27:6443")
            .build();

    public static ExtendedKubernetesClient getClient() throws Exception {
        return new ExtendedKubernetesClient(config);
    }

    public static VirtualMachine getVMByName(String name) throws Exception {
        return getClient().virtualMachines().get(name);
    }

    public static VirtualMachineImage getVMImageByName(String name) throws Exception {
        return getClient().virtualMachineImages().get(name);
    }

    public static VirtualMachineDisk getVMDiskByName(String name) throws Exception {
        return getClient().virtualMachineDisks().get(name);
    }

    public static VirtualMachinePool getVMPoolByName(String name) throws Exception {
        return getClient().virtualMachinePools().get(name);
    }

    public static VirtualMachineDiskImage getVMDiskImageByName(String name) throws Exception {
        return getClient().virtualMachineDiskImages().get(name);
    }

    public static VirtualMachineNetwork getVMNetworkByName(String name) throws Exception {
        return getClient().virtualMachineNetworks().get(name);
    }
}
