/**
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.kubesys.kubernetes.impl;

import java.util.regex.Pattern;

import com.github.kubesys.kubernetes.api.model.VirtualMachinePool;
import com.github.kubesys.kubernetes.api.model.VirtualMachinePoolList;
import com.github.kubesys.kubernetes.api.model.VirtualMachinePoolSpec;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.AutoStart;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.CreatePool;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.DeletePool;
//import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.RegisterPool;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.StartPool;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.StopPool;
import com.github.kubesys.kubernetes.api.model.virtualmachinepool.Lifecycle.UnregisterPool;
import com.github.kubesys.kubernetes.utils.RegExpUtils;

/**
 * @author  wuheng@otcaix.iscas.ac.cn
 * 
 * @version 1.0.0
 * @since   2019/9/1
 **/
public class VirtualMachinePoolImpl extends AbstractImpl<VirtualMachinePool, VirtualMachinePoolList, VirtualMachinePoolSpec> {

	@Override
	public VirtualMachinePool getModel() {
		return new VirtualMachinePool();
	}

	@Override
	public VirtualMachinePoolSpec getSpec() {
		return new VirtualMachinePoolSpec();
	}
	
	@Override
	public Object getLifecycle() {
		return new Lifecycle();
	}

	
	@Override
	public VirtualMachinePoolSpec getSpec(VirtualMachinePool r) {
		return r.getSpec();
	}

	/*************************************************
	 * 
	 * Generated by <code>MethodGenerator<code>
	 * 
	 **************************************************/
	public boolean autoStart(String name, AutoStart autoStart) throws Exception {
		return autoStart(name, autoStart, null);
	}

	public boolean autoStart(String name,AutoStart autoStart, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return update(name, updateMetadata(name, eventId), autoStart);
	}

	public boolean createPool(String name, CreatePool createPool) throws Exception {
		return createPool(name, null, createPool, null);
	}

	public boolean createPool(String name, String nodeName, CreatePool createPool) throws Exception {
		return createPool(name, nodeName, createPool, null);
	}

	public boolean createPool(String name, CreatePool createPool, String eventId) throws Exception {
		return createPool(name, null, createPool, eventId);
	}

	public boolean createPool(String name, String nodeName,CreatePool createPool, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return create(getModel(), createMetadata(name, nodeName, eventId), 
				createSpec(nodeName, createLifecycle(createPool)));
	}

	public boolean startPool(String name, StartPool startPool) throws Exception {
		return startPool(name, startPool, null);
	}

	public boolean startPool(String name,StartPool startPool, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return update(name, updateMetadata(name, eventId), startPool);
	}

//	public boolean registerPool(String name, RegisterPool registerPool) throws Exception {
//		return registerPool(name, registerPool, null);
//	}
//
//	public boolean registerPool(String name,RegisterPool registerPool, String eventId) throws Exception {
//		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
//		if (!pattern.matcher(name).matches()) {
//			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
//		}
//		return update(name, updateMetadata(name, eventId), registerPool);
//	}

	public boolean stopPool(String name, StopPool stopPool) throws Exception {
		return stopPool(name, stopPool, null);
	}

	public boolean stopPool(String name,StopPool stopPool, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return update(name, updateMetadata(name, eventId), stopPool);
	}

	public boolean deletePool(String name, DeletePool deletePool) throws Exception {
		return deletePool(name, deletePool, null);
	}

	public boolean deletePool(String name,DeletePool deletePool, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return delete(name, updateMetadata(name, eventId), deletePool);
	}

	public boolean unregisterPool(String name, UnregisterPool unregisterPool) throws Exception {
		return unregisterPool(name, unregisterPool, null);
	}

	public boolean unregisterPool(String name,UnregisterPool unregisterPool, String eventId) throws Exception {
		Pattern pattern = Pattern.compile(RegExpUtils.NAME_PATTERN);
		if (!pattern.matcher(name).matches()) {
			throw new IllegalArgumentException("the length must be between 4 and 100, and it can only includes a-z, 0-9 and -.");
		}
		return update(name, updateMetadata(name, eventId), unregisterPool);
	}

}