/**
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.kubesys.kubernetes.impl;

import com.github.kubesys.kubernetes.api.model.VirtualMachineImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineImageList;
import com.github.kubesys.kubernetes.api.model.VirtualMachineImageSpec;
import com.github.kubesys.kubernetes.api.model.virtualmachineimage.Lifecycle;
import com.github.kubesys.kubernetes.api.model.virtualmachineimage.Lifecycle.ConvertImageToVM;
import com.github.kubesys.kubernetes.api.model.virtualmachineimage.Lifecycle.CreateImage;
import com.github.kubesys.kubernetes.api.model.virtualmachineimage.Lifecycle.DeleteImage;

/**
 * @author  wuheng@otcaix.iscas.ac.cn
 * 
 * @version 1.0.0
 * @since   2019/9/1
 **/
public class VirtualMachineImageImpl extends AbstractImpl<VirtualMachineImage, VirtualMachineImageList, VirtualMachineImageSpec> {

	@Override
	public VirtualMachineImage getModel() {
		return new VirtualMachineImage();
	}

	@Override
	public VirtualMachineImageSpec getSpec() {
		return new VirtualMachineImageSpec();
	}

	@Override
	public Object getLifecycle() {
		return new Lifecycle();
	}

	@Override
	public VirtualMachineImageSpec getSpec(VirtualMachineImage r) {
		return r.getSpec();
	}

	/*************************************************
	 * 
	 * Generated by <code>MethodGenerator<code>
	 * 
	 **************************************************/

	public boolean createImage(String name, CreateImage createImage) throws Exception {
		return createImage(name, null, createImage, null);
	}

	public boolean createImage(String name, String nodeName, CreateImage createImage) throws Exception {
		return createImage(name, nodeName, createImage, null);
	}

	public boolean createImage(String name, CreateImage createImage, String eventId) throws Exception {
		return createImage(name, null, createImage, eventId);
	}

	public boolean createImage(String name, String nodeName,CreateImage createImage, String eventId) throws Exception {
		return create(getModel(), createMetadata(name, nodeName, eventId), 
				createSpec(nodeName, createLifecycle(createImage)));
	}

	public boolean deleteImage(String name, DeleteImage deleteImage) throws Exception {
		return deleteImage(name, deleteImage, null);
	}

	public boolean deleteImage(String name,DeleteImage deleteImage, String eventId) throws Exception {
		return delete(name, updateMetadata(name, eventId), deleteImage);
	}

	public boolean convertImageToVM(String name, ConvertImageToVM convertImageToVM) throws Exception {
		return convertImageToVM(name, convertImageToVM, null);
	}

	public boolean convertImageToVM(String name,ConvertImageToVM convertImageToVM, String eventId) throws Exception {
		return update(name, updateMetadata(name, eventId), convertImageToVM);
	}

}
